### ISSUE TITLE
Basic examples from the README fail with ArgumentError

### ISSUE THREAD

**Issue by brandonzylstra** [rafaelsales/whenever-test#8]
This is almost directly taken from the README, with the addition of 2 requires which were missing from the example, and other trivial changes, but it fails every time with an ArgumentError:

```ruby
require 'spec_helper'
require 'whenever'
require 'whenever/test'

describe 'Whenever Schedule' do
  before do
    load 'Rakefile'
  end

  # binding.irb  # ← the line that fails below will work if I paste it into irb

  it 'makes sure there are 2 update_employee_data jobs' do
    schedule = Whenever::Test::Schedule.new(file: 'config/schedule.rb')  # ← this line fails ALWAYS
    employee_update_jobs = schedule.jobs[:runner]

    assert_equal 2, employee_update_jobs.count

    schedule.jobs[:runner].each { |job| instance_eval job[:task] }
  end

end
```

Here's the Rspec failure: 

```rspec
  1) Whenever Schedule makes sure there are 2 update_employee_data jobs
     Failure/Error: schedule = Whenever::Test::Schedule.new(file: 'config/schedule.rb')

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # (eval):158:in `parse'
     # ./spec/whenever_spec.rb:13:in `new'
     # ./spec/whenever_spec.rb:13:in `block (2 levels) in <top (required)>'
```

The strange thing is that if I put in a `binding.irb` in the location you see it commented out in the code, then `schedule = Whenever::Test::Schedule.new(file: 'config/schedule.rb')` will work fine.  

After digging into it much more, I think I found the problem:  whenever-test assumes that `runner` lines are only used with e.g. 'SomeModel.some_method', while `rails runner` also works with ruby scripts, where it sets up the Rails environment before running the Ruby code.  

The fix is probably a matter of

1. first checking whether the argument represents a class and a method, and proceeding the same as currently if so
2. otherwise treating the argument as a path to a ruby script and testing it similarly to a `script` line.

**Comment by matiasmasca** [comment]
I received the same message but when I had a problem on the config/schedule.rb file
